"
A base visitor to traverse `SpPanelArea`
"
Class {
	#name : 'SpPanelAreaVisitor',
	#superclass : 'Object',
	#category : 'Spec-Panel-Presenter',
	#package : 'Spec-Panel',
	#tag : 'Presenter'
}

{ #category : 'visiting' }
SpPanelAreaVisitor >> visitBottom: anArea [
]

{ #category : 'visiting' }
SpPanelAreaVisitor >> visitCenter: anArea [
]

{ #category : 'visiting' }
SpPanelAreaVisitor >> visitEnd: anArea [
]

{ #category : 'visiting' }
SpPanelAreaVisitor >> visitStart: anArea [
]

{ #category : 'visiting' }
SpPanelAreaVisitor >> visitTop: anArea [
]
